-- 2.1.1
SELECT c.CONTINENTE, COUNT(c.NOMBRE) AS NUM_GP
FROM CARRERA c 
GROUP BY c.CONTINENTE
HAVING COUNT(c.NOMBRE) > 3 
ORDER BY COUNT(c.NOMBRE) DESC
;
-- 2.1.2
SELECT c.NOMBRE AS GP, c.FECHA, c.UBICACION, c.CONTINENTE
FROM CARRERA c
WHERE c.FECHA BETWEEN TO_DATE('2024-10-01', 'yyyy-mm-dd')
AND TO_DATE('2024-11-01', 'yyyy-mm-dd')
AND LOWER(c.CONTINENTE) = 'america' 
;
-- 2.2.1
SELECT e.NOMBRE AS ESCUDERIA, AVG(p.EDAD) AS EDAD_MEDIA 
FROM ESCUDERIA e
JOIN PILOTO p ON (e.ID_ESCUDERIA = p.ID_ESCUDERIA)
WHERE e.ID_ESCUDERIA IN (
	SELECT p2.ID_ESCUDERIA 
	FROM PILOTO p2 
	WHERE LOWER(p2.NACIONALIDAD) = 'españa'
	)
GROUP BY e.NOMBRE
;
-- 2.2.2
SELECT p.NOMBRE AS PILOTO, e.NOMBRE AS ESCUDERIA 
FROM PILOTO p 
JOIN ESCUDERIA e ON (p.ID_ESCUDERIA = e.ID_ESCUDERIA)
JOIN CARRERA c ON (p.ID_PILOTO = c.ID_CAMPEON)
WHERE p.EDAD > 25
GROUP BY p.NOMBRE, e.NOMBRE
HAVING COUNT(c.ID_CAMPEON) >= 1
;
-- 2.3.1
SELECT p.NOMBRE AS PILOTO, p.NACIONALIDAD, r.NOMBRE, r.PAIS AS PAIS_REPRE 
FROM PILOTO p
LEFT JOIN REPRESENTANTE r ON (p.ID_REPRESENTANTE = r.ID_REPRESENTANTE)
ORDER BY p.NOMBRE, r.NOMBRE
;
-- 2.3.2
SELECT i.NOMBRE AS INGENIERO, i.ESPECIALIDAD, e.NOMBRE AS ESCUDERIA, 
i2.NOMBRE AS JEFE_INGENIERIA
FROM INGENIERO i
LEFT JOIN INGENIERO i2 ON (i.ID_JEFE = i2.ID_INGENIERO)
JOIN ESCUDERIA e ON (i.ID_ESCUDERIA = e.ID_ESCUDERIA)
ORDER BY e.NOMBRE DESC, i.NOMBRE DESC
;
-- 2.4.1
SELECT p.NOMBRE AS PILOTO, p.EDAD, e.NOMBRE AS ESCUDERIA, NVL(COUNT(C.ID_CAMPEON), 0) AS VICTORIAS
FROM PILOTO p 
JOIN ESCUDERIA e ON (p.ID_ESCUDERIA = e.ID_ESCUDERIA)
LEFT JOIN CARRERA c ON (p.ID_PILOTO = c.ID_CAMPEON)
GROUP BY p.NOMBRE, p.EDAD, e.NOMBRE
ORDER BY e.NOMBRE, p.NOMBRE
;
-- 2.5.1
DROP VIEW VICTORIAS_POR_PAIS_VW;

CREATE VIEW VICTORIAS_POR_PAIS_VW AS
SELECT p.NACIONALIDAD AS PAIS, COUNT(DISTINCT p.ID_PILOTO) AS NUM_PILOTOS, COUNT(c.ID_CAMPEON) AS VICTORIAS 
FROM PILOTO p
LEFT JOIN CARRERA c ON (p.ID_PILOTO = c.ID_CAMPEON)
GROUP BY p.NACIONALIDAD
ORDER BY p.NACIONALIDAD;